CREATE TABLE role (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rolename VARCHAR(50)
);

CREATE TABLE person (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id INT,
    name VARCHAR,
    phone_no BIGINT,
    email VARCHAR UNIQUE,
    entry_date DATE,
    gender VARCHAR(10),
    accommodation_status VARCHAR(20),
    created_at TIMESTAMP DEFAULT now(),
    FOREIGN KEY (role_id) REFERENCES role(id)
);

CREATE TABLE house_info (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR,
    location VARCHAR,
    description TEXT,
    created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE room (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_no VARCHAR,
    bath INT,
    number_of_room INT,
    floor_no INT,
    rent DECIMAL(10,2),
    house_id INT NOT NULL,
    FOREIGN KEY (house_id) REFERENCES house_info(id)
);

CREATE TABLE allocation (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id INT NOT NULL,
    room_id INT NOT NULL,
    start_date DATE,
    end_date DATE,
    status VARCHAR(20),
    FOREIGN KEY (person_id) REFERENCES person(id),
    FOREIGN KEY (room_id) REFERENCES room(id)
);

CREATE TABLE payment (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id INT,
    amount DECIMAL(10,2),
    payment_date DATE,
    payment_method VARCHAR(20),
    status VARCHAR(20),
    FOREIGN KEY (person_id) REFERENCES person(id)
);

CREATE TABLE maintenance_request (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id INT,
    person_id INT,
    request_date DATE,
    description TEXT,
    status VARCHAR(20),
    FOREIGN KEY (room_id) REFERENCES room(id),
    FOREIGN KEY (person_id) REFERENCES person(id)
);
